"use client";

import {useMemo,useState} from "react";
import {api} from "@/lib/api";
import {useLoadOnMount} from "@/lib/useResource";
import {Activity,Copy,KeyRound,MonitorCog,RefreshCw,ShieldCheck,WifiOff} from "lucide-react";
import {Alert,Badge,Button,Card,EmptyState,Input,Select,SelectContent,SelectItem,SelectTrigger,Spinner} from "@gerege-systems/ui";
import { formatMoment } from "@/lib/datetime";

type Device={id:string;name:string;platform:string;form_factor:string;site:string;status:string;app_version:string;os_version:string;last_seen_at?:string;enrolled_at:string};
type Member={membership_id:string;name:string;email:string};

export default function DeviceFleetPage(){
  const [devices,setDevices]=useState<Device[]>([]),[members,setMembers]=useState<Member[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const [code,setCode]=useState<{value:string;expires:string}|null>(null),[pin,setPin]=useState(""),[member,setMember]=useState("");
  async function load(){setLoading(true);setError("");try{const [fleet,access]=await Promise.all([api.getDevices(),api.getAccessOverview()]);setDevices(fleet.devices);setMembers(access.members);setMember(v=>v||access.members[0]?.membership_id||"")}catch(e){setError(e instanceof Error?e.message:"Төхөөрөмжийн парк ачаалсангүй")}finally{setLoading(false)}}
  useLoadOnMount(load);
  const now=Date.now(),online=devices.filter(d=>d.last_seen_at&&now-new Date(d.last_seen_at).getTime()<5*60_000).length;
  const groups=useMemo(()=>Object.entries(devices.reduce<Record<string,Device[]>>((all,d)=>{(all[d.site||"Байршилгүй"]??=[]).push(d);return all},{})),[devices]);
  async function issue(){setError("");try{const result=await api.createDeviceEnrollmentCode();setCode({value:result.code,expires:result.expires_at})}catch(e){setError(e instanceof Error?e.message:"Код үүсгэсэнгүй")}}
  async function savePin(){if(!member||!/^[0-9]{4,12}$/.test(pin))return;setError("");try{await api.setStaffPin(member,pin);setPin("");setNotice("Ажилтны PIN шинэчлэгдлээ");setTimeout(()=>setNotice(""),2500)}catch(e){setError(e instanceof Error?e.message:"PIN хадгалсангүй")}}
  if(loading)return <div className="p-8 flex items-center gap-2 text-sm text-muted" role="status"><Spinner size="md" decorative/>Төхөөрөмжийн паркийг шалгаж байна…</div>;
  return <div className="mx-auto w-full max-w-[1500px] space-y-6">
    <header className="grid gap-5 border-b border-line pb-6 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="font-mono text-xs font-semibold uppercase tracking-[.22em] text-accent">Fleet control / live registry</p><h1 className="mt-2 flex items-center gap-3 text-3xl font-semibold tracking-tight text-foreground"><MonitorCog className="h-8 w-8 text-accent" aria-hidden="true"/>Төхөөрөмжийн парк</h1><p className="mt-2 max-w-2xl text-sm text-muted">Windows ба Android kiosk/POS, mobile client-үүдийн enrollment, төлөв, ажилтны хурдан нэвтрэлтийг нэг цэгээс удирдана.</p></div><Button variant="outline" leadingIcon={<RefreshCw/>} onClick={()=>void load()}>Дахин шалгах</Button></header>
    {error&&<Alert variant="danger" live>{error}</Alert>}{notice&&<Alert variant="success" live>{notice}</Alert>}
    <section className="grid gap-4 sm:grid-cols-3"><Metric label="Нийт бүртгэл" value={devices.length} hint="device identity"/><Metric label="Сүүлийн 5 минутад" value={online} hint="online heartbeat" tone="success"/><Metric label="Анхаарах" value={devices.filter(d=>d.status!=="ACTIVE"||!d.last_seen_at).length} hint="offline / inactive" tone="warning"/></section>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><section className="min-w-0 space-y-5">{groups.length===0?<Card padding="none"><EmptyState icon={<WifiOff className="size-6"/>} title="Бүртгэлтэй төхөөрөмж алга" description="Баруун талд нэг удаагийн код үүсгээд native Device Settings-д оруулна уу." headingLevel={2} className="py-10"/></Card>:groups.map(([site,items])=><Card key={site} padding="none" className="overflow-hidden"><div className="flex items-center justify-between border-b border-line bg-surface-2 px-4 py-2"><h2 className="font-mono text-xs font-semibold uppercase tracking-wider text-foreground">{site}</h2><span className="text-xs text-muted">{items.length} төхөөрөмж</span></div><div className="divide-y divide-line">{items.map(d=><DeviceRow key={d.id} device={d} online={!!d.last_seen_at&&now-new Date(d.last_seen_at).getTime()<5*60_000}/>)}</div></Card>)}</section>
      <aside className="space-y-5"><Card asChild padding="lg"><section><div className="flex items-center gap-2"><KeyRound className="h-5 w-5 text-accent" aria-hidden="true"/><h2 className="font-semibold text-foreground">Enrollment code</h2></div><p className="mt-2 text-xs leading-5 text-muted">Код 10 минут, зөвхөн нэг удаа хүчинтэй. Device token буцааж харуулахгүй.</p>{code?<div className="mt-5 rounded-md border border-accent bg-accent-soft p-4"><Button variant="ghost" trailingIcon={<Copy/>} onClick={()=>void navigator.clipboard.writeText(code.value)} className="h-auto w-full justify-between px-0 font-mono text-xl font-semibold tracking-[.12em] text-accent hover:bg-transparent"><span className="truncate">{code.value}</span></Button><p className="mt-2 font-mono text-xs text-muted">ДУУСАХ: {formatMoment(code.expires)}</p></div>:null}<Button className="mt-5 w-full" onClick={()=>void issue()}>{code?"Шинэ код үүсгэх":"Код үүсгэх"}</Button></section></Card>
      <Card asChild padding="lg"><section><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-foreground" aria-hidden="true"/><h2 className="font-semibold text-foreground">Ажилтны PIN</h2></div><p className="mt-2 text-xs leading-5 text-muted">POS/tablet дээр ажилтан хурдан солих 4–12 оронтой credential.</p><div className="mt-4 flex flex-col gap-1.5"><label htmlFor="staff-pin-member" className="text-sm font-medium text-foreground">Ажилтан</label><Select value={member} onValueChange={setMember}><SelectTrigger id="staff-pin-member"/><SelectContent>{members.map(m=><SelectItem key={m.membership_id} value={m.membership_id}>{m.name} · {m.email}</SelectItem>)}</SelectContent></Select></div><Input className="mt-3" type="password" label="Шинэ PIN" inputMode="numeric" autoComplete="new-password" value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,"").slice(0,12))}/><Button className="mt-4 w-full" disabled={!member||!/^[0-9]{4,12}$/.test(pin)} onClick={()=>void savePin()}>PIN хадгалах</Button></section></Card></aside>
    </div>
  </div>
}
function Metric({label,value,hint,tone}:{label:string;value:number;hint:string;tone?:"success"|"warning"}){return <Card padding="none" className="px-5 py-4"><p className="font-mono text-xs uppercase tracking-[.2em] text-muted">{label}</p><div className="mt-1 flex items-baseline gap-3"><strong className={`text-4xl font-semibold tabular-nums ${tone==="success"?"text-success":tone==="warning"&&value>0?"text-warning":"text-foreground"}`}>{value}</strong><span className="font-mono text-xs text-subtle">{hint}</span></div></Card>}
function DeviceRow({device:d,online}:{device:Device;online:boolean}){function toggle(){void api.setDeviceStatus(d.id,d.status==="ACTIVE"?"DISABLED":"ACTIVE").then(()=>location.reload())}return <article className="grid gap-3 p-4 md:grid-cols-[12px_minmax(160px,1fr)_130px_1.2fr_auto] md:items-center"><span aria-hidden="true" className={`h-3 w-3 rounded-full ${online?"bg-success-solid":"bg-line-strong"}`}/><div className="min-w-0"><h3 className="font-semibold text-foreground">{d.name}</h3><code className="text-xs text-muted">{d.id}</code></div><div><span className="block font-mono text-xs font-semibold uppercase text-accent">{d.platform} / {d.form_factor}</span><button type="button" onClick={toggle} title="Төлөв солих" className="mt-1 rounded-full focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><Badge variant="subtle" tone={d.status==="ACTIVE"?"success":"neutral"}>{d.status}</Badge></button></div><div className="min-w-0 text-xs text-muted"><span className="block truncate">{d.os_version||"OS тодорхойгүй"}</span><span className="block truncate text-muted">App {d.app_version||"—"}</span></div><div className="text-right font-mono text-xs text-muted"><Activity className="mb-1 ml-auto h-4 w-4" aria-hidden="true"/>{d.last_seen_at?formatMoment(d.last_seen_at):"холбогдоогүй"}</div></article>}
